#mongodb://localhost:27017/
spring:
    application:
        name: activity-service
    data:
        mongodb:
          uri: mongodb://localhost:27017/Fitnessactivities
          database: Fitnessactivities


server:
  port: 8082


eureka:
  client:
    service-Url:
      defaultZone: http://localhost:8761/eureka