spring:
  application:
    name: ai-sevice
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessrecommendation
      database: fitnessrecommendation
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


eureka:
  client:
    service-Url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8083


rabbitmq:
  exchange:
    name: fitness-exchange
  queue:
    name: activity-queue
  routing:
    key: activity-tracking