spring:
  application:
    name: healthcare-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/HealthcareDB
      database: HealthcareDB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

rabbitmq:
  healthcare:
    exchange:
      name: healthcare-exchange
    queue:
      name: healthcare-queue
    routing:
      key: symptom-data